import 'controller/android_large_twentyfour_tab_container_controller.dart';import 'package:matka/core/app_export.dart';import 'package:matka/presentation/android_large_twentyfour_page/android_large_twentyfour_page.dart';import 'package:matka/widgets/app_bar/appbar_leading_image.dart';import 'package:matka/widgets/app_bar/appbar_title.dart';import 'package:matka/widgets/app_bar/custom_app_bar.dart';import 'package:matka/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class AndroidLargeTwentyfourTabContainerScreen extends GetWidget<AndroidLargeTwentyfourTabContainerController> {const AndroidLargeTwentyfourTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: 360.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 6.v), child: Column(children: [_buildAccountDetailsName(), SizedBox(height: 28.v), _buildAccountDetailsIFSCCode(), SizedBox(height: 29.v), _buildAccountDetailsAccountNumber(), SizedBox(height: 30.v), _buildAccountDetailsAccountNumber2(), SizedBox(height: 28.v), _buildAccountDetailsEmail(), SizedBox(height: 53.v), _buildTabview(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildTabBarView())); }
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 51.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 27.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft();}), title: Container(height: 24.v, width: 178.h, margin: EdgeInsets.only(left: 19.h), child: Stack(alignment: Alignment.center, children: [AppbarTitle(text: "msg_add_account_details".tr), AppbarTitle(text: "msg_add_account_details".tr)]))); }
/// Section Widget
Widget _buildAccountDetailsName() { return Container(margin: EdgeInsets.only(right: 8.h), padding: EdgeInsets.symmetric(horizontal: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_account_name".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 4.v), CustomTextFormField(controller: controller.nameController, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL23)])); }
/// Section Widget
Widget _buildAccountDetailsIFSCCode() { return Padding(padding: EdgeInsets.only(right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_ifsc_code".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 2.h), child: CustomTextFormField(controller: controller.editTextController, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL23))])); }
/// Section Widget
Widget _buildAccountDetailsAccountNumber() { return Padding(padding: EdgeInsets.only(right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_account_number".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 4.v), CustomTextFormField(controller: controller.editTextController1, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL23)])); }
/// Section Widget
Widget _buildAccountDetailsAccountNumber2() { return Padding(padding: EdgeInsets.only(right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_account_number2".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 3.v), CustomTextFormField(controller: controller.editTextController2, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL23)])); }
/// Section Widget
Widget _buildAccountDetailsEmail() { return Padding(padding: EdgeInsets.only(right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_email".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 2.h), child: CustomTextFormField(controller: controller.emailController, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL23))])); }
/// Section Widget
Widget _buildTabview() { return Container(height: 47.v, width: 302.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(23.h), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))]), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.black900.withOpacity(0.25), labelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400), unselectedLabelColor: appTheme.whiteA700, unselectedLabelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400), indicatorPadding: EdgeInsets.all(3.5.h), indicator: BoxDecoration(color: appTheme.blueGray100.withOpacity(0.35), borderRadius: BorderRadius.circular(20.h)), tabs: [Tab(child: Text("lbl_enter_otp2".tr)), Tab(child: Text("lbl_request_otp".tr))])); }
/// Section Widget
Widget _buildTabBarView() { return Container(margin: EdgeInsets.only(left: 53.h, right: 53.h, bottom: 31.v), height: 128.v, child: TabBarView(controller: controller.tabviewController, children: [AndroidLargeTwentyfourPage(), AndroidLargeTwentyfourPage()])); }

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); }
 }
