import 'controller/bet_eight_tab_container_controller.dart';import 'package:matka/core/app_export.dart';import 'package:matka/presentation/bet_eight_page/bet_eight_page.dart';import 'package:matka/widgets/custom_elevated_button.dart';import 'package:matka/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class BetEightTabContainerScreen extends GetWidget<BetEightTabContainerController> {const BetEightTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: 360.h, child: Column(children: [SizedBox(height: 47.v), Column(children: [_buildArrowLeftRow(), SizedBox(height: 22.v), _buildViewRow(), SizedBox(height: 61.v), _buildEditTextColumn(), SizedBox(height: 29.v), _buildTabview(), _buildTabBarView()])])))); }
/// Section Widget
Widget _buildArrowLeftRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 32.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgArrowLeft();}), Spacer(), CustomImageView(imagePath: ImageConstant.imgWallet, height: 25.adaptSize, width: 25.adaptSize), Padding(padding: EdgeInsets.only(left: 2.h, top: 4.v), child: Text("lbl_10".tr, style: theme.textTheme.bodyLarge))])); }
/// Section Widget
Widget _buildViewRow() { return Container(margin: EdgeInsets.symmetric(horizontal: 20.h), padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 15.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Container(height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 3.v, bottom: 19.v), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.black900.withOpacity(0.5), width: 2.h))), Container(width: 77.h, margin: EdgeInsets.only(left: 3.h, top: 3.v), child: Text("msg_open_pana_close".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumRegular)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 19.v), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.black900.withOpacity(0.5), width: 2.h))), Container(width: 80.h, margin: EdgeInsets.only(left: 3.h, top: 2.v), child: Text("msg_close_pana_open".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumRegular))])); }
/// Section Widget
Widget _buildEditTextColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Padding(padding: EdgeInsets.only(left: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("lbl_open_digit".tr, style: theme.textTheme.titleLarge)), CustomTextFormField(width: 120.h, controller: controller.editTextController, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15)])), SizedBox(height: 17.v), Padding(padding: EdgeInsets.only(left: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 4.v), child: Text("lbl_close_pana".tr, style: theme.textTheme.titleLarge)), CustomTextFormField(width: 120.h, controller: controller.editTextController1, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15)])), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 4.v), child: Text("lbl_enter_points2".tr, style: theme.textTheme.titleLarge)), Container(height: 30.v, width: 120.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(15.h), border: Border.all(color: appTheme.black900, width: 1.h, strokeAlign: strokeAlignOutside)))])), SizedBox(height: 17.v), CustomElevatedButton(height: 30.v, width: 120.h, text: "lbl_add_bet".tr, buttonStyle: CustomButtonStyles.outlineBlackTL51, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700, alignment: Alignment.centerRight)])); }
/// Section Widget
Widget _buildTabview() { return Container(height: 40.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.25)), child: TabBar(controller: controller.tabviewController, isScrollable: true, tabs: [Tab(child: Text("lbl_game_type".tr)), Tab(child: Text("lbl_close_digit".tr)), Tab(child: Text("lbl_open_pana".tr)), Tab(child: Text("lbl_amount".tr))])); }
/// Section Widget
Widget _buildTabBarView() { return SizedBox(height: 342.v, child: TabBarView(controller: controller.tabviewController, children: [BetEightPage(), BetEightPage(), BetEightPage(), BetEightPage()])); }

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); }
 }
