import 'controller/android_large_twentyseven_controller.dart';import 'package:matka/core/app_export.dart';import 'package:matka/widgets/app_bar/appbar_title.dart';import 'package:matka/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class AndroidLargeTwentysevenScreen extends GetWidget<AndroidLargeTwentysevenController> {const AndroidLargeTwentysevenScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: 360.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 29.v), child: Column(children: [_buildTransactionDetailRow(), SizedBox(height: 5.v), SizedBox(height: 560.v, width: 321.h, child: Stack(alignment: Alignment.topCenter, children: [_buildDoctorReviewsRow(), _buildClientTestimonialsRow(), _buildReviewsStack(), Align(alignment: Alignment.center, child: SizedBox(width: 321.h, child: Divider())), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 168.v), child: SizedBox(width: 321.h, child: Divider()))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 90.h), child: SizedBox(height: 557.v, child: VerticalDivider(width: 1.h, thickness: 1.v)))), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 127.h), child: SizedBox(height: 557.v, child: VerticalDivider(width: 1.h, thickness: 1.v)))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 55.v), child: SizedBox(width: 321.h, child: Divider()))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 111.v), child: SizedBox(width: 321.h, child: Divider()))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 105.v), child: SizedBox(width: 319.h, child: Divider()))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 50.v), child: SizedBox(width: 319.h, child: Divider()))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 164.v), child: SizedBox(width: 319.h, child: Divider())))]))])))); }
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 57.h, leading: Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 33.h, top: 15.v, bottom: 16.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center, onTap: () {onTapImgArrowLeft();}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)])), title: AppbarTitle(text: "msg_transaction_detail".tr, margin: EdgeInsets.only(left: 13.h))); }
/// Section Widget
Widget _buildTransactionDetailRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 89.h, padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 6.v), decoration: AppDecoration.outlineBlack9002, child: Text("lbl_date".tr, style: CustomTextStyles.bodyMediumRobotoWhiteA700)), Container(width: 105.h, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 6.v), decoration: AppDecoration.outlineBlack9002, child: Text("lbl_point".tr, style: CustomTextStyles.bodyMediumRobotoWhiteA700)), Container(width: 127.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 6.v), decoration: AppDecoration.outlineBlack9002, child: Text("lbl_add_withdraw".tr, style: CustomTextStyles.bodyMediumRobotoWhiteA700))]); }
/// Section Widget
Widget _buildDoctorReviewsRow() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(top: 335.v, right: 2.h), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.fillWhiteA, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_12_36_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 30.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_12_00_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 24.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_11_10_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 22.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_10_00_pm".tr, style: theme.textTheme.bodySmall)])), Padding(padding: EdgeInsets.only(top: 8.v, right: 43.h, bottom: 5.v), child: Column(children: [_buildUserProfileRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr), SizedBox(height: 46.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildRecentOrdersRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr)), SizedBox(height: 39.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildRecentOrdersRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr)), SizedBox(height: 34.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildRecentOrdersRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr))]))]))); }
/// Section Widget
Widget _buildClientTestimonialsRow() { return Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(bottom: 227.v), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.fillWhiteA, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_17_12_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_9_01_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 20.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_5_36_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 28.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_2_54_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 30.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_2_12_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 24.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_2_10_pm".tr, style: theme.textTheme.bodySmall), SizedBox(height: 22.v), Text("lbl_20_10_2023".tr, style: theme.textTheme.bodySmall), Text("lbl_1_00_pm".tr, style: theme.textTheme.bodySmall)])), Padding(padding: EdgeInsets.only(top: 7.v, right: 24.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 146.h, margin: EdgeInsets.only(left: 1.h, right: 17.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_500".tr, style: theme.textTheme.bodySmall), Text("lbl_add".tr, style: theme.textTheme.bodySmall)])), SizedBox(height: 41.v), SizedBox(width: 164.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_2500".tr, style: theme.textTheme.bodySmall), Text("lbl_withdraw".tr, style: theme.textTheme.bodySmall)])), SizedBox(height: 37.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 17.h), child: _buildUserProfileRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr)), SizedBox(height: 46.v), Padding(padding: EdgeInsets.only(left: 5.h, right: 17.h), child: _buildRecentOrdersRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr)), SizedBox(height: 39.v), Padding(padding: EdgeInsets.only(left: 5.h, right: 17.h), child: _buildRecentOrdersRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr)), SizedBox(height: 34.v), Padding(padding: EdgeInsets.only(left: 5.h, right: 17.h), child: _buildRecentOrdersRow(dynamicText1: "lbl_500".tr, dynamicText2: "lbl_add".tr))]))]))); }
/// Section Widget
Widget _buildReviewsStack() { return Align(alignment: Alignment.topCenter, child: Container(height: 1.v, width: 321.h, margin: EdgeInsets.only(top: 228.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 321.h, child: Divider())), Align(alignment: Alignment.center, child: SizedBox(width: 321.h, child: Divider()))]))); }
/// Common widget
Widget _buildRecentOrdersRow({required String dynamicText1, required String dynamicText2, }) { return SizedBox(width: 142.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(dynamicText1, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.black900)), Text(dynamicText2, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.black900))])); }
/// Common widget
Widget _buildUserProfileRow({required String dynamicText1, required String dynamicText2, }) { return SizedBox(width: 143.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text(dynamicText1, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.black900))), Text(dynamicText2, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.black900))])); }

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); }
 }
