// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVSYxWlSMeIu-tKNF-NpLSpHs-CPTklQ',
    appId: '1:809182134007:web:958dc731787f1ec998ddf2',
    messagingSenderId: '809182134007',
    projectId: 'prarambh-edae4',
    authDomain: 'prarambh-edae4.firebaseapp.com',
    storageBucket: 'prarambh-edae4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt1-FWmgsGs70VoEKsHBvilCz8k0Fn-2Q',
    appId: '1:809182134007:android:6066e7b5136a846b98ddf2',
    messagingSenderId: '809182134007',
    projectId: 'prarambh-edae4',
    storageBucket: 'prarambh-edae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrT7m__LFaxgXQUi0XxElQpY0r_v8ELY',
    appId: '1:809182134007:ios:a0faa6628108ca4198ddf2',
    messagingSenderId: '809182134007',
    projectId: 'prarambh-edae4',
    storageBucket: 'prarambh-edae4.appspot.com',
    iosBundleId: 'com.dharmendrasapplication.app',
  );
}
